---
title: "Ordination"
format: html
editor: visual
---

## Event ordination

Is there a way to ordinate events based on diversity of spectral peaks? Could we use the techniques developed by ecologists to describe differences between diverse ecological communities? If we were to do this, an acoustic event would be analogous to a community, and each click would be analogous to a different taxon within that community. The distance between events would be calculated in the same way as the ecological metric beta diversity, where the range of different spectral peaks would be considered as well as the abundance of those varying peaks.

```{r}
library(vegan)

#Function that will be used to bin clicks using a desired parameter
source("R/countClicks.R")

#Bin all clicks on Channel 1 by peak frequency using bin width = 0.1 kHz
bins <- spectra %>% 
  countClicks(param = peak, ch = 1, binw = 0.1)

#Use vegan::vegdist() to calculate distances between events using the Bray method
set.seed(123)
dist <- vegdist(bins$m, method = "bray")

#Use NMDS to ordinate events
nmds <- metaMDS(dist)

#Plot results of NMDS
scores(nmds) %>%
  as_tibble(rownames = "eventId") %>%
  inner_join(filter(metadata, Channel == 1), by = "eventId") %>%
  ggplot(aes(x = NMDS1, y = NMDS2, color = species))+
  geom_point()
```

We could also try rarefying the data which would help control for the differences between events that are due to the difference in sampling effort. This is relevant because we do have a wide array of sampling depths across our different events, with n ranging from \<10 to \>2000.
